### ISSUE TITLE
Could you give me some hint? Thanks!

### ISSUE THREAD

**Issue by newforrestgump001** [reunanen/anno#9]
When run anno, it shows that QImage::pixelIndex: Not applicable for 8-bpp images (no palette) and no written json file.

**Comment by reunanen** [comment]
Yeah, there are some assumptions in the submodule code about the image containing a palette. I too have run into this message; it should not be critical in any way (at least for me everything works as expected, even if I get this message). That said, I'll surely fix it at some point.

If your image doesn't open at all, could you please attach the image file, so that I could try to reproduce the problem?

As for json files, anno currently does not write any – but if you have some available (e.g. produced using [convert-result-images-to-anno-paths](https://github.com/reunanen/convert-result-images-to-anno-paths)), it may be able to read and show some external (inference) results.

**Comment by JackGan999** [comment]
Thank you Juha Reunanen! I can open the image and paint the area using mark defect, but I don't know how to get the mask image.
Could you tell me to get mask image?
Thanks,
Jack

**Comment by JackGan999** [comment]
Thank you Juha Reunanen! I know how to get the mask image now. But how to save the annotated data, since maybe I want to reedit the anntoation later.
Thanks a lot!

**Comment by reunanen** [comment]
@JackGan999 : Sorry, not exactly sure what you are asking. I mean – the mask image _is_ the annotated data, no? :)

**Comment by JackGan999** [comment]
@reunanen I mean the JSON data. Since it is convenient to save, I think.

**Comment by JackGan999** [comment]
@reunanen On ubuntu, anno couldn't save the mask image. What is the possible reason?
It shows QIODevice::read (QFile, "/home/pc/Downloads/img/test1.jpg_result_path.json"): device not open

**Comment by reunanen** [comment]
@JackGan999 Currently, no JSON data is saved for the annotations. But it should be quite easy to generate something like that from the mask images. You could use [this code](https://github.com/reunanen/convert-result-images-to-anno-paths/blob/master/convert-result-images-to-anno-paths.cpp) as an example.

**Comment by JackGan999** [comment]
@reunanen I got it, thanks for your replay!

**Comment by reunanen** [comment]
@JackGan999 

> It shows QIODevice::read (QFile, "/home/pc/Downloads/img/test1.jpg_result_path.json"): device not open

Want to test again with the latest version?

**Comment by JackGan999** [comment]
@reunanen , Of cource, I will test the latest verison. By the way, have you commited the latest version to the github?

**Comment by reunanen** [comment]
@JackGan999 : Yes, [this commit](https://github.com/reunanen/anno/commit/2ca2fa17fc5b3264cfd566b4b08fbe5b6617547b) should fix the "device not open" issue.

**Comment by JackGan999** [comment]
@reunanen Thank you very much! It works.
